name: website

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
permissions: write-all

concurrency:
  group: ${{ github.workflow }}-website-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deployment:
    runs-on: ubuntu-latest
    # Skip for forks, dependabot PRs and the release PR
    if:
      github.event.pull_request.head.repo.full_name == github.repository || github.event_name ==
      'push' && github.event.pull_request.head.repo.fork != true && github.actor !=
      'dependabot[bot]'
    steps:
      - name: checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0

      - uses: the-guild-org/shared-config/setup@v1
        name: setup env
        with:
          node-version-file: .node-version

      - uses: the-guild-org/shared-config/website-cf@v1
        name: build and deploy website
        env:
          NEXT_BASE_PATH: ''
          SITE_URL: ${{ github.ref == 'refs/heads/master' && 'https://fets.dev' || '' }}
        with:
          cloudflareApiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflareAccountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: fets
          prId: ${{ github.event.pull_request.number }}
          websiteDirectory: ./
          buildScript: cd website && npm run build
          artifactDir: website/out
